INSERT INTO players (name) VALUES ('Alisson');
INSERT INTO players (name) VALUES ('Ederson');
INSERT INTO players (name) VALUES ('Weverton');
INSERT INTO players (name) VALUES ('Danilo');
INSERT INTO players (name) VALUES ('Dani Alves');
INSERT INTO players (name) VALUES ('Guilherme Arana');
INSERT INTO players (name) VALUES ('Alex Telles');
INSERT INTO players (name) VALUES ('Alex Sandro');
INSERT INTO players (name) VALUES ('Eder Militão');
INSERT INTO players (name) VALUES ('Gabriel Magalhães');
INSERT INTO players (name) VALUES ('Marquinhos');
INSERT INTO players (name) VALUES ('Thiago Silva');
INSERT INTO players (name) VALUES ('Bruno Guimarães');
INSERT INTO players (name) VALUES ('Casemiro');
INSERT INTO players (name) VALUES ('Danilo');
INSERT INTO players (name) VALUES ('Fabinho');
INSERT INTO players (name) VALUES ('Fred');
INSERT INTO players (name) VALUES ('Lucas Paquetá');
INSERT INTO players (name) VALUES ('Philipe Coutinho');
INSERT INTO players (name) VALUES ('Gabriel Jesus');
INSERT INTO players (name) VALUES ('Gabriel Martinelli');
INSERT INTO players (name) VALUES ('Matheus Cunha');
INSERT INTO players (name) VALUES ('Richarlison');
INSERT INTO players (name) VALUES ('Neymar');
INSERT INTO players (name) VALUES ('Raphinha');
INSERT INTO players (name) VALUES ('Rodrygo');
INSERT INTO players (name) VALUES ('Vinicius Jr');